// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif
#include "/home/linux/project_zzh/include/list.h"
#include "/home/linux/project_zzh/include/queue.h"
#include "/home/linux/project_zzh/include/mailbox.h"
#include<stdio.h>
// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(Link_t *pmail);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

