// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(Link_t *pmail)
{
    Que_Data_t data;
    char buf[100] = {0};
    recv_msg(pmail,&data);
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -240);
    lv_obj_set_y(ui_Label1, -213);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    sprintf(buf,"温度： %.2f 湿度: %.2f",data.temp,data.hum);
    lv_label_set_text(ui_Label1, buf);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1fs, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -153);
    lv_obj_set_y(ui_Label3, -127);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    sprintf(buf,"三轴加速度： x: %.2f y: %.2f z: %.2f",data.x,data.y,data.z);
    lv_label_set_text(ui_Label3, buf);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font1fs, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -216);
    lv_obj_set_y(ui_Label4, -52);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    sprintf(buf,"光照强度： %.2f",data.light);
    lv_label_set_text(ui_Label4, buf);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font1fs, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label1 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;

}
